### PR TITLE
Mirror puppet-module-mofed nm_controlled behavior

### PR DESCRIPTION
**Pull request by pedmon**
For comparison see: https://github.com/treydock/puppet-module-mofed/pull/23

### CODE REVIEW

**Comment by treydock** [comment]
Lint issues are missing documentation at top of file.  Something like this:

```
# @param nm_controlled
#   Value for nm_controlled on interface
```

**Comment by treydock** [comment]
If you rebase against master or merge master into this pull request, that should fix the broken testing.

**Comment by pedmon** [comment]
Okay, rebased.  Let me know if you need any other changes.

**Comment by treydock** [comment]
The unit tests fixtures need updates to account for changed contents of ifcfg files.  Similar to here: https://github.com/treydock/puppet-module-mofed/pull/23/files

**Comment by pedmon** [comment]
Gotcha. I will work on adding those.

-Paul Edmon-

**Comment by pedmon** [comment]
Done.

**Comment by treydock** [comment]
This will be released with v4.1.0 once Github Actions complete.

**Pull request merged**
